export const strings = {
  client: 'client',
  worker: 'worker',
  unkown_step: 'Unknown stepIndex',
  once: 'Once',
  ongoing: 'Ongoing',
  signup_error: 'Please fill in all fields and make sure to agree on terms of use and privacy policy',
  signup_confirmation: 'I confirm that I, as the account holder, am over 18 years of age and have read and agree with Kindle’s Terms of Use and Privacy Policy.',
  profile_fetch_user_error: 'Error retrieving user info. Please contact Kindle support',
  signin_url: '/signin',
  message_send_error: 'Sending message failed',
  message_apply_job: 'Failed to get job. It might have been deleted',
  applyjob_error: 'Please select a day and time before adding',
  pending: 'Pending',
  offer_send_error: 'Error sending offer. Please contact Kindle support',
  signup_url: '/signup',
  home_url: '/',
  dashboard_url: '/dashboard',
  search_url: '/search',
  timesheets_url: '/timesheets',
  jobs_url: '/jobs',
  messages_url: '/messages',
  client_bio: `I am looking for a great new support worker to help me with a bunch of my weekly activities, as well as some personal care activities to get ready in the morning.
    I am 22 years old and my real passion is computer science. I have a lot of experience with computers and want to work as an IT technician on day. Apart from that I love to go to the movies and out with friends.
    I have severe, spastic, quadriplegic cerebral palsy and I use wheelchair. I have some difficulties with communication, but once you get to understand me, we will get on just fine.`,
  signupThankyou: 'Thank you for signing up!',
  signupVerification: 'A verification mail has been sent to your email address. Please check your inbox or junk mail to verify',
  verificationEmailResend: 'Another verification email has been sent to your email address.',
  worker_bio: ` I'm an energetic, enthusiastic and reliable individual. I don’t have any experience in the disability sector, but I’d love to develop my skills and build relationships with people. I’m available for all types of work, especially getting out and about in the community. My particular passion is working with young adults in order to support growth, development, independence and autonomy.
  I love dreaming up unusual new recipes and laughing in good company. I'm also a big believer in the ability of all people to contribute to the community and hope to assist as many people as I can through Kindle.`,
  worker_age_preference: 'If you would like to work with teenagers or children you will need a current, paid Working with Children Check and a current and paid Disability Services Employment check (volunteer checks are no longer accepted).',
  financial_info_discalimer: "We collect your financial information so we can pay you. As with everything you tell us, it's important to know that this information will not be shared with anyone.",
  legal_name_disclaimer: 'This will only be used on your pay slips and with the ATO and will not appear publicly on your profile.',
  payroll_disclaimer: 'Payroll happens once a fortnight so any shifts you complete in a two week window will be paid all at once at the end of each fortnight.',
  payments_disclaimer: 'Superannuation payments are made quarterly by: 28 January, 28 April, 28 July and 28 October.',
  tax_disclaimer: 'These details are required in order to determine the amount of tax to withhold from your pay. Your information is protected by our privacy statement.',
  CPR: "Please upload a copy of your CPR, First Aid, or basic emergency life support certificate. Kindle only accepts the following certificates and doesn't accept a receipt for a course.",
  ndis_orientation_1: 'The NDIS Quality and Safeguards Commission has launched an',
  ndis_orientation_2: 'to assist workers in the disability sector to better support people with disability.',
  ndis_message: 'We encourage all our registered support workers to create an account, log in to the NDIS Quality and Safeguards Commission website and complete the online training course. This training is a requirement to become a Kindle employee.',
  working_with_children_message: "Please ensure that the Working With Children check you have uploaded is for employment purposes. Kindle doesn't accept volunteer purpose checks.",
  police_check: 'We cannot accept volunteer purpose police checks.',
  police_check_duration: 'This must be issued within the last 12 months, to you, not another organisation.',
  transportAgreement_disclaimer: 'By providing transport as a support worker with Kindle, you enter into our Transport Agreement for Support Workers.',
  truthful_info_disclaimer: 'I certify that, to the best of my knowledge, I have answered questions in this application truthfully and have not omitted any details in answering each question. I understand and acknowledge that if I have knowingly given false answers to any of the questions or omitted any details in answering any question in this application, my status and insurance coverage through Kindle may be affected.',
  service_agreement_disclaimer: 'acknowledge that I accept the terms of this Agreement with Kindle Pty Ltd on the terms and conditions set out above. I also acknowledge and agree that I am entering this Agreement electronically and ticking this box constitutes my signature to enter into this Agreement.',
  age_disclaimer: 'By ticking this box you confirm that you are over 18 years of age and that you have read and agree with our Terms of Use, and Privacy Policy.',
  home_header_1: 'Kindle Your Abilities',
  home_header_2: 'Unleash Your Power',
  about_kindle_1: 'Our name, Kindle, recognises the power of human potential. It’s inspired by the ability of human beings to unlock the energy within. We believe in you and believe we can help you make your dreams come true.',
  about_kindle_2: 'With Kindle, you are able to choose the services you want, from whom, when and at what price.',
  about_kindle_3: 'With Kindle, you are able to continue living independently in your own home and remain connected with your community',
  restrictivePracticesTooltip: "A restrictive practice is any practice or intervention that has the effect of restricting the rights of freedom of movement of a person with disability, with the primary purpose of protecting the person or others from harm. This could include seclusion, using medication to influence a person's behaviour, using physical force to restrain a person, using equipment to restrain someone's movement or preventing access to certain places.",
  client_referee: 'Get verified by providing contact details for a character referee. This might be a person in your support network (such as a support coordinator) who you would be comfortable for us to contact as your account is created. We will contact this person if we need to confirm information.',
  client_financial: "We collect financial information so we can arrange payroll and invoicing services. As with everything you tell us, it's important to know that this information will not be shared with anyone.",
}

export const arrays = {
  client_Registration: ['Personal Information', 'Disability information', 'Referee', 'Financial Information', 'Agreement'],
  worker_Registration: ['Personal Information', 'Support work', 'Qualification', 'Referee', 'Financial Information', 'Upload Documents', 'Agreement'],
  days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  supportTimeEachWeekArray: ['0 - 5 hours per week', '6 - 10 hours per week', '11 - 15 hours per week',
    '16 - 20 hours per week', '21 - 25 hours per week', '26 - 30 hours per week', '30+ hours per week'],
  supportTypeArray: [{ title: 'Help around the house', toolTip: 'Help around the house is important for you to be able to remain independently at home. This might include help in the graden, home-office duties and keeping the house tidy by assisting with laundry, taking out the rubbish or feeding pets.' },
    { title: 'In-home care', toolTip: 'In-home care is important to help you maintain your independence. This includes assistance with morning and evening routines, showring and toileting, mealtime preparation and medication reminders.' },
    { title: 'Personal care', toolTip: 'Personal care and hygiene support is important for maintaining an active and social lifestyle. This might include toileting (in the home or out in the community) and mealtime assistance' },
    { title: 'Outdoor care', toolTip: 'This might include anything from shopping to fitness, to joining a new community group to social events.' },
    { title: 'Education, training and employment', toolTip: 'This might include assisting you at school, in the classroom or in the playground, at university or TAFE, in the workplace or to develop new skills.' },
    { title: 'Therapy support', toolTip: 'Therapy support is designed to help you if you have an early intervention, developmental services, physiotherapy, occupational therapy or speech pathology plan. Your worker will follow your individualised program to help with the ongoing implementation of your therapy at home and in other environments.' },
    { title: 'Transport', toolTip: "Transport support is helping you to get ready, accompanying and providing assistance at the destination, and ensuring you return home safely. Depending on your worker's preference this might be in your car or theirs." }],
  unpaidWorkExperienceOptions: ['Providing informal support for a family member',
    'Providing informal support for a friend or neighbour',
    'Doing a placement through study or coursework',
    'Volunteering in another setting'],
  ageGroupsOptions: ['Adults', 'Teenagers', 'Children'],
  workTypeOptions: ['Ongoing', 'Once off'],
  workAvailabilityOptions: ['Weekdays', 'Evenings', 'Weekends'],
  educationOptions: ['Primary education', 'Secondary education', 'Certificate level', 'Advanced diploma and diploma level',
    'Bachelor degree level', 'Postgraduate degree level'],
  areaOfEducationOptions: ['Natural and Physical Sciences', 'Information Technology', 'Engineering and Related Technologies',
    'Architecture and Building', 'Agriculture, Environmental and Related Studies', 'Health', 'Education', 'Management and Commerce',
    'Society and Culture', 'Creative Arts', 'Food, Hospitality and Personal Services'],
  refereeRelationshipOptions: ['Manager', 'Client', 'Teacher', 'Colleague', 'Employee'],
  refereeRelationshipLengthOptions: ['less than 6 months', '6 to 12 months', 'more than 12 months'],
  refereeExtraRelationshipOptions: ['Friend', 'Other'],
  australianResidentForTaxPurpose: ['You have always lived in Australia or have come to Australia and now live here permanently', 'You are an overseas student doing a course that takes more than six months to complete', 'You migrated to Australia and intend to reside here permanently'],
  taxFreeThreshold: ['You are not currently claiming the tax-free threshold from another payer', 'You are currently claiming the tax-free threshold from another payer and your total income from all sources will be less than $18,200.'],
  firstaidOptions: ['CPR certificates (HLTAID001 or HLTAID007, valid for 1 year)', 'Basic emergency life support (HLTAID002, valid for 1 year)', 'First Aid certificates (HLTAID003, HLTAID004, HLTAID006, valid for 3 years)'],
  transportAgreement_terms: ['Commit to safe driver behaviour, to protect myself and others. e.g. be alert, observe laws, defensive driving, manage fatigue levels and fitness to drive.',
    'Provide a current and valid drivers licence to Kindle when you choose to provide transport. An updated copy must be provided as it approaches expiry.',
    'Get in contact with Kindle immediately if you have any licence issues such as cancellation or restrictions.',
    'Notify Kindle of any medical condition that may prevent you from safely providing transport.',
    'Ensure driver and all passengers wear a seatbelt while in motion.',
    'Ensure that you have an appropriate load restraint system and/or cargo barriers in place if you are carrying a heavy load, e.g. a wheelchair or other equipment',
    'Agree to complete a Kindle online incident form in the case of any incident or near miss event.',
    ['You must not:', 'Consume alcohol or drugs between the time the booking commences and ceases.', 'Drive or attempt to put the vehicle in motion, while there is any concentration of alcohol or drugs present in your blood', 'Exceed the passenger limits of the vehicle.', 'Use a hand held mobile phone or two-way radios while operating the vehicle.'],
    ['If you drive the vehicle of a person seeking support with Kindle you agree to:', 'Request to see a copy of the registration certificate of the vehicle prior to driving.', 'Request to see a copy of the Compulsory Third Party (CTP) insurance for the vehicle.', 'Request to see a copy of any other insurance policies.', 'Complete a visual inspection of the vehicle prior to driving to ensure it is safe.', "Request training from the vehicle's owners, to ensure you understand how to effectively operate the vehicle."],
    ['If you use your own vehicle to provide transport with Kindle you agree to:', 'Maintain the vehicle in a safe, clean and roadworthy condition. Conduct a visual Vehicle Inspection Checklist annually.', "Ensure the vehicle is maintained and serviced, as outlined in the owner's manual.", 'Register your vehicle with the relevant body and ensure the registration is maintained.', 'Hold Compulsory Third Party (CTP) and check that you are insured to drive for business purposes.', 'Think about your insurance needs and consider obtaining Comprehensive Insurance.', 'Keep accurate records of the trips you have made using your own vehicle.', 'Consider keeping a first aid kit in your vehicle.', 'Provide Kindle with copies of any of these records when requested.', 'Understand that I am fully responsible for my vehicle in the event of any claim that arises as a result of an accident, in conjunction with my insurer.']],
}
